<a href="https://colab.research.google.com/github/Varun24-ch/AIML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype =float)

SyntaxError: invalid non-printable character U+00A0 (<ipython-input-6-f724f387b862>, line 3)

In [7]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)

In [8]:
a

array([1, 2, 3])

In [9]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
d = np.array([5,6,7])

In [11]:
e=a+d

In [12]:
e

array([ 6,  8, 10])

In [14]:
f = np.array([(3.5,4,8),(7,8,9)],dtype = float)

In [15]:
f

array([[3.5, 4. , 8. ],
       [7. , 8. , 9. ]])

In [16]:
g=b+f

In [17]:
g

array([[ 5.,  6., 11.],
       [11., 13., 15.]])

In [18]:
b = f = np.array([(7,3,1),(14,15,29)], dtype = float)

In [19]:
f

array([[ 7.,  3.,  1.],
       [14., 15., 29.]])

In [20]:
f.sort()

In [21]:
f


array([[ 1.,  3.,  7.],
       [14., 15., 29.]])